
- name: Cassnada seed list fact
  set_fact: cassandra_seed_list="{{ cassandra_seeds | join(',') }}"

- debug: var=cassandra_seed_list

- name: Set JVM options
  template: src=files/jvm.j2 dest=/etc/cassandra/jvm.options backup=true

- name: Set Cassandra config file
  template: src=files/cassandra.j2 dest=/etc/cassandra/cassandra.yaml backup=true

- name: Check Cassandra system.log existence
  stat: path=/var/log/cassandra/system.log
  register: system_log_file

- name: Clear Cassandra system.log
  when: system_log_file.stat.exists == True
  shell: echo > /var/log/cassandra/system.log

- name: Cassandra startup
  service: name=cassandra state=started

- name: Wait for server autostart
  wait_for: path=/var/log/cassandra/system.log search_regex="Starting listening for CQL clients"

